[build]
base = "/"
publish = "build"
command = "npm run build"

[build.environment]
GENERATE_SOURCEMAP = "false"

# Redirect for API requests
[[redirects]]
from = "/api/*"
to = "http://efficio-dev.eba-333pnkfu.us-east-1.elasticbeanstalk.com/:splat"
status = 200
force = true

# Redirect for SPA (React)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
