[build]
  base = "/"
  publish = "build"
  command = "npm run build"
[build.environment]
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/api/*"
  to = "https://efficio-dev.eba-333pnkfu.us-east-1.elasticbeanstalk.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
